runtime: nodejs
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
env_variables:
  ATLAS_URI: "mongodb+srv://mahsook:mahsook123@timelytask.zoa2ti3.mongodb.net/?retryWrites=true&w=majority"
  PORT: 8080
